---
title: "Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
    source: embed
---

```{r setup, include=FALSE}
library(tidyverse)
library(p8105.datasets)
library(plotly)
library(flexdashboard)
```

```{r}
data("instacart")

instacart = 
  instacart %>% 
  select(order_id, reordered, order_dow, order_hour_of_day, product_name, aisle_id,  aisle, department) %>% 
  filter(
    order_id %in% 1000:20000
  ) 
```

Column {data-width=650}
-----------------------------------------------------------------------

### Chart A: Number of orders for each department under each aisle

```{r}
instacart_count =
  instacart %>% 
  count(aisle)

instacart = 
  left_join(instacart, instacart_count)

y = list(
  title = "number of orders"
)

instacart %>% 
  mutate(text_label = str_c("Department: ", department, "\nAisle: ", aisle, "\nNumber of orders: ", n)) %>% 
  plot_ly(x = ~department, y = ~n, alpha = 0.5,
          color = ~n, text = ~text_label,
          type = "scatter", mode = "markers") %>% 
  layout(yaxis = y)
```

Column {data-width=350}
-----------------------------------------------------------------------

### Chart B: Order hour of the day distribution for each deapartment

```{r}
x = list(
  title = "order hour of the day"
)

instacart %>% 
  filter(
    !(department == "missing" | department == "other")) %>% 
  mutate(
    department = reorder(department, order_hour_of_day)) %>% 
  plot_ly(x = ~order_hour_of_day, y = ~department,
          color = ~department, type = "box", colors = "viridis") %>% 
  layout(xaxis = x)
```

### Chart C: Top 15 best selling products

```{r}
x = list(
  title = "product name",
  tickangle = 20
)

y = list(
  title = "number of order"
)

instacart %>% 
  count(product_name) %>% 
  arrange(desc(n)) %>% 
  slice(1:15) %>% 
  mutate(
    product_name = reorder(product_name, n)) %>% 
  plot_ly(x = ~product_name, y = ~n, color = ~product_name,
          type = "bar", colors = "viridis") %>% 
  layout(xaxis = x, yaxis = y)
```

